# DO NOT EDIT THIS FILE!
#
# Python module ogata_lab__POA generated by omniidl

import omniORB
omniORB.updateModule("ogata_lab__POA")

# ** 1. Stub files contributing to this module
import CarSimulator_idl

# ** 2. Sub-modules

# ** 3. End
